spring.application.name=cartify
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:mysql://localhost:3306/cartify_db?createDatabaseIfNotExist=true&useSSL=false&allowPublicKeyRetrieval=true&serverTimezone=UTC}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:root}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:}
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

spring.jpa.database-platform=org.hibernate.dialect.MySQLDialect
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true

cartify.cors.allowed-origin=${ALLOWED_ORIGIN:http://localhost:3000}
google.client.id=1080216648204-bkf0khd6f1oqr9d363e4kvkmidlkski6.apps.googleusercontent.com

# Serving static files and templates
spring.thymeleaf.prefix=classpath:/templates/
spring.thymeleaf.suffix=.html
spring.thymeleaf.cache=false
